name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec: 
        description: Run by cypress command line
        default: cypress/e2e/*
        
jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
        
      - name: Cypress run
        uses: cypress-io/github-action@v5.3.1
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: be025bde-602f-40e6-8e88-52480e893a4c
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
